### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by kucher93** [qZhenya-dev/berachain#1]
Привет, разрабы наверное что то изменили, ошибка
Exception in thread Thread-2 (start):
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'bartio-faucet.berachain-devnet.com'. (_ssl.c:1007)

**Comment by next-softs** [comment]
Привет, да изменили, все поправил
